### ISSUE TITLE
Some problems with dlls other than ntdll.dll

### ISSUE THREAD

**Issue by syrex1013** [JustasMasiulis/wow64pp#6]
Hey,
Could you provide some info about hooking dlls other than ntdll.dll?
I used this lib in my other project(compiled in VS19), but now doing:
`    auto x64_ntdll_handle = wow64pp::module_handle("Kernel32.dll");
`
Return error that the library could not be loaded.
Any idea why?

**Comment by JustasMasiulis** [comment]
What is the error exactly? Because the lookup is case sensitive and `kernel32.dll` will probably work.

**Comment by syrex1013** [comment]
![obraz](https://user-images.githubusercontent.com/31669127/99099402-ad912180-25da-11eb-9dbf-bfa9f1def876.png)
Here it is.
I also tried with kernel32.dll but it does not work. Same error!

**Comment by JustasMasiulis** [comment]
Try placing a breakpoint on the name comparison and check if you can spot the correct name and whether it's iterating the list at all.

**Comment by syrex1013** [comment]
Sorry, it was some error on my end. I placed the breakpoint and it iterated list good. Idk why it wasn't working
