### ISSUE TITLE
Included in new project, redefinition errors.

### ISSUE THREAD

**Issue by syrex1013** [JustasMasiulis/wow64pp#7]
Hey,
After including in new project, I get "GetModuleHandleA" redefinition errors.
Error codes C2371,C2733.
I solved it somehow in my other project but can't remember how.
Any ideas?

**Comment by syrex1013** [comment]
Nvm, solved, for anyone having same problem, add compiler option:
/Zc:externC- %(AdditionalOptions)

**Comment by nblog** [comment]
I have the same problem as you.
but I tried to fix it so it can work normally.
https://github.com/nblog/wow64pp/commit/e7bf2e55d7858c310297dd59263d05fbeee59fd0
hope it can help people with the same problem.
